### ISSUE TITLE
Characters

### ISSUE THREAD

**Issue by Ragonfana** [TJChap2840/TerrariViewer#98]
My characters can be selected, however when selected, their names are a complete mess. MY mana is "540416, and my health is "0" and full. nothing on my character loads.

**Comment by supernozcraft** [comment]
yea i cicked save and my character i worked so hard on is ALL GONE im so mad i cant even explain it right now

**Comment by TerrariMaster** [comment]
Hey, try using terrasvr, its an awsome, web-based editor, so it saves all of your stuff and there are all the cool things in terraria 1.3
heres the link: yal.cc/r/terrasavr/
